/**
 * File
 *
 * @module      :: Modely
 * @description :: A short summary of how this model works and what it represents.
 * @docs		:: http://sailsjs.org/#!documentation/models
 */

module.exports = {

  schema: true,

  attributes: {
  	
  	user_id: { // This matches the autogenerated id (by the DB) in the user model (pseudo foreign-key)
  		type: 'integer'
  	},

  	file_type: {
 		type: 'string'
 	},

 	file_name: {
 		type: 'string'
 	},

 	file_path: {
 		type: 'string'
 	},

 	file_size: {
 		type: 'integer'
 	},

 	title: {
 		type: 'string'
 	},

 	description: {
 		type: 'string'
 	},

 	file_cdn_public_id: {
 		type: 'string'
 	},

    file_cdn_version: {
 		type: 'string'
 	},
    
    file_cdn_signature: {
 		type: 'string'
 	},

    file_format: {
 		type: 'string'
 	},

    file_cdn_url: {
 		type: 'string'
 	},

    file_cdn_secure_url: {
 		type: 'string'
 	},

 	//Now the thumbnail attributes
 	file_thumb_cdn_url: {
 		type: 'string'
 	},

 	file_thumb_cdn_secure_url: {
 		type: 'string'
 	},
    
  }

};